default_context:
  project_name: 'foodoo-app'
  project_slug: 'foodoo-app'
  domain_main: 'dev.foodoo.dev'
  domain_staging: 'stage.foodoo.dev'
  docker_swarm_stack_name_main: 'foodoo-dev'
  docker_swarm_stack_name_staging: 'stage-foodoo-dev'
  secret_key: '41405811ee24f7db55cd00b80d79ca62c8fadd526a9a40c548da5bdd9dd8b231'
  first_superuser: 'admin@foodoo.dev'
  first_superuser_password: 'Falsedevilsalad4314pis'
  backend_cors_origins: '["http://localhost","http://localhost:8080","https://localhost","https://localhost:8080","https://dev.foodoo.dev","https://stag.foodoo.dev","https://foodoo.dev"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@foodoo.dev'
  postgres_password: 'Falsedevilsalad4314pis'
  pgadmin_default_user: 'admin@foodoo.dev'
  pgadmin_default_user_password: 'Falsedevilsalad4314pis'
  traefik_constraint_tag: 'foodoo.dev'
  traefik_constraint_tag_staging: 'stage.foodoo.dev'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Falsedevilsalad4314pis'
  sentry_dsn: 'https://314645ecaae849eeb2bc58884b6feba7@o567628.ingest.sentry.io/5754545'
  docker_image_prefix: 'app/'
  docker_image_backend: 'app/backend'
  docker_image_celeryworker: 'app/celeryworker'
  docker_image_frontend: 'app/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
