version: '3.9'
services:
  backend:
    image: openinfolabs/osintbuddy-backend:latest
    command: ['/bin/sh', '-c', './start-reload.sh']
    build:
      context: ./backend
      dockerfile: 'backend.Dockerfile'
    volumes:
      - ./backend/app:/app/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - 5000:80
    env_file:
      - .env
  microservice:
    image: openinfolabs/osintbuddy-microservice:latest
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - 1323:1323
    env_file:
      - '.env'
  db:
    image: postgres:14.2
    volumes:
      - osintbuddy-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
  worker:
    image: openinfolabs/osintbuddy-worker:latest
    command: /worker-start.sh
    build:
      context: ./backend
      dockerfile: worker.Dockerfile
    env_file:
      - .env
  flower:
    image: mher/flower:1.2
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379//
  # rya:
  #   image: ktipp/rya-docker-dev:latest
  #   ports:
  #     - 8080:8080
  #     - 2181:2181
  #   environment:
  #     HOSTNAME: 0.0.0.0
  #     ZOOKEEEPERS: rya
  #     ZOO_MY_ID: 1
  #   networks:
  #     - rya_dev
  
  
  # frontend:
  #   image: openinfolabs/osintbuddy-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/nginx.conf:/etc/nginx/nginx.conf

networks:
  rya_dev:

volumes:
  osintbuddy-db-data:
